language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

#create database
before_script:
  - psql -c 'create database books_test_db;' -U postgres

# command to run tests
script:
  #- pytest tests/.
  - pytest --cov=api
  - coverage report

after_script:
  - codeclimate-test-reporter --token  $CODE_CLIMATE_TOKEN
